[package]
name = "snake_game"
version = "0.1.0"
description = "A simple snake game"
authors = ["Apoorv Verma [AP]"]
edition = "2021"
license = "None"
repository = ""

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.82"

[dependencies.web-sys]
version = "0.3"
features = [
  "console"
]