[package]
name = "snake_game"
version = "0.1.0"
description = "A simple snake game"
authors = ["Apoorv Verma [AP]"]
edition = "2021"
repository = ""

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { version = "0.2.82", features = ["serde-serialize"] }
wee_alloc = "0.4.5"
rand = "0.8.5"
getrandom = { version = "0.2", features = ["js"] }
js-sys = "0.3.59"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.82"

[dependencies.web-sys]
version = "0.3"
features = [
  "console",
  "Window",
  "Document",
]